### ISSUE TITLE
HTML Lists 

### ISSUE THREAD

**Issue by alimbaeva** [BrightBrainsKk/Section-2#2]
Снять видео и написать код.

**Comment by ShahzadaMamatisaeva** [comment]
Для записей видео урока ушло 2 дня, сперва подготовила презентации и повторила пройденную тему. А потом сняла видео.

**Comment by ShahzadaMamatisaeva** [comment]
[
[Web Development.zip](https://github.com/BrightBrainsKk/second-section/files/7001469/Web.Development.zip)
](url)
