### ISSUE TITLE
HTML Image Elements (Шахзада)

### ISSUE THREAD

**Issue by alimbaeva** [BrightBrainsKk/Section-2#3]
Снять видео и написать код.

**Comment by alimbaeva** [comment]
записала за 2 дня
[css-my-site.zip](https://github.com/BrightBrainsKk/second-section/files/7001517/css-my-site.zip)

**Comment by ShahzadaMamatisaeva** [comment]
[Web Development.zip](https://github.com/BrightBrainsKk/second-section/files/7001530/Web.Development.zip)
Резюме

**Comment by ShahzadaMamatisaeva** [comment]
1. Сняла видео по этой теме.
2. [web-dovelopment.zip](https://github.com/BrightBrainsKk/second-section/files/7007909/web-dovelopment.zip)
